pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/varnish
        tags: [6.0.0, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
